# Generated by Django 5.2 on 2025-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_orderkey_remove_order_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
