# Generated by Django 5.2 on 2025-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderkey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
