# Generated by Django 5.2 on 2025-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketkey',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
