# Generated by Django 5.2 on 2025-04-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='offers')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
