# Generated by Django 5.2 on 2025-04-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
