# Generated by Django 5.2 on 2025-04-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='offers'),
        ),
    ]
